// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwirgxwiwgptnycqgkqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aXJneHdpd2dwdG55Y3Fna3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTQzNjEsImV4cCI6MjA2NzczMDM2MX0.tPKH7VhrUfvZu6E1YHDdFByLUmbQbPhqtGasK_9B0Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});